# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend
#   namespace: expense
# data:
#   DB_HOST: mysql # mysql component service name

---
apiVersion: webs/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    component: frontend
    project: expense
    tier: web 
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: web
        environment: dev
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1.0
        envFrom:
        - configMapRef:
            name: frontend



---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: nodePort
  selector:
    component: frontend
    project: expense
    tier: web
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80