apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    cource: k8
    trainer: shiva
  annotations:
    Kubernetes.io/created-by: "ram"
    jenkins.build.url: 'https://jenkins.daws78s.online/expense/job/backend/54'
spec:
  containers:
  - name: nginx
    image: nginx