apiVersion: v1
kind: Pod
metadata:
  name: resource-limit
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
     # soft limit
      requests:
        memory: "68Mi"
        cpu: "100m"
      # limits should be atleast or more than requests i.e hard limit
      limits:
        memory: "128Mi"
        cpu: "125m"
