apiVersion: v1
kind: service
metadata:
  name: ngix-service
spec:
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - portocol: TCP
    port: 80 # service port
    targetPort: 80 # target-port