apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-example
  # these labels beongs to repica set resource
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: frontend
      environment: dev
  # below is pod defination
  template:
    metadata:
      labels:
        tier: frontend
        app: frontend
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:stabel-perl
        