
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-eaxmple
  # these labels belongs to deployment resource
  labels:
    app: nginx
    tier: frontend
    purpose: depoyment
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: web
      environment: dev
  # below is pod defination
  template:
    metadata:
      labels:
        tier: frontend
        app: web
        environment: dev
        project: expense
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
     # soft limit
          requests:
            memory: "68Mi"
            cpu: "100m"
      # limits should be atleast or more than requests i.e hard limit
          limits:
            memory: "128Mi"
            cpu: "125m"
        



---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myhpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment-eaxmple
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
