apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    component: backend
    project: expense
    tier: app 
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
        environment: dev
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1.0
        envFrom:
        - configMapRef:
            name: backend



---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
    environment: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080